version: '2'
services:
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes:
            - 'mysql_data:/var/lib/mysql'
    adminer:
        image: adminer
        ports:
            - 8080:8080
    web:
        build: .
        ports:
            - '8000:80'
            - '3001:3001'
        volumes:
            - 'web_data:/web'
            - './:/home/project-folder'
        depends_on:
            - mysql
        stdin_open: true
        tty: true
volumes:
    mysql_data:
        driver: local
    web_data:
        driver: local
